site:
    title: "镜中阁"
    subtitle: "仰天大笑出门去，我辈岂是蓬蒿人"
    theme: theme
    lang: zh-CN
    url: "https://blog.jiaxuanlee.com"
authors:
    me:
        id: 1
        name: "阁主"
        Name: "测试"
        intro: "相思难表，梦魂无据，惟有归来是"