wrk.method = "POST"
wrk.body   = "{\"text\":\"### 1. 斜体和粗体和粗斜体\n使用 \\* 和 \\*\\* 和 \\*\\*\\* 表示斜体和粗体。\n这是 *斜体*，这是 **粗体**，这是***粗斜体***\n\n### 2. 删除线\n使用 \\~\\~ 表示删除线\n这是 ~~删除线~~，这是 ~~删除线+***粗斜体***~~\n\n### 3. 外链接\n使用 \\[描述](链接地址) 为文字增加外链接。\n这是一个链接：[李佳轩的个人网站——***镜中之人***](https://www.jiaxuanlee.com)\n\n### 4. 行内底色变色强调\n使用\\`表示行内底色变色强调。\n这是一个`行内底色变色强调。[李佳轩的个人网站——***镜中之人***](https://www.jiaxuanlee.com)`。\n\n### 小技巧\n可以使用转义符来表示符号本身的意思，否则，会认为使用了markdown的语法。\n如：使用 \\* 和 \\*\\* 表示斜体和粗体。\"}"
wrk.headers["Content-Type"] = "text/plain; charset=utf-8"
wrk.headers["Origin"] = "http://localhost:63342"
wrk.headers["Referer"] = "http://localhost:63342/leeBlogCli/test/myBlog.html?_ijt=mg0898tqjo365k6ph3bgtldpth"
wrk.headers["User-Agent"] = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
