wrk.method = "POST"
wrk.body   = "{\"text\":\"~s*打双打a~~打算sda1*das哒2*~~\n这是一个连接：[李佳轩的个人博客——*镜中之人*](http://www.jiaxuanlee.com)\n# [JDB-H5-UI-VUE](http://git.jdb-dev.com/zen/jdb-h5-ui)\n\n### 首次使用\n仓库克隆到本地以后，首先执行。这条命令会做一些必要的准备工作。\n然后你再进行常规的等等操作。所有npm命令的具体含义可以查看本文档的npm命令部分\n\n### 开发组件库的组件\n确保自己已经在项目根目录\n1. 在src目录下新建自己的组件目录（如button）。\n2. 在刚刚新建的组件目录下新建文件index.js。js的内容形如（button为例）：\n\n3. 在组件目录下新建一个src目录，在src目录下新建对应组件的vue文件。然后开始开发组件。\n\n开发组件的时候可能需要调试或者开发完成后想写一个demo试试自己开发的组件。可以参考本文档的调试组件部分。\n\n### 调试组件\nsites目录下是一个整的vue项目。如果想要调试组件。可以修改sites/debug/index.vue文件的内容\n比如要调试button组件。sites/debug/index.vue文件中可以引入src目录下的button组件来作为自己的一个组件去调试，即：\n写好之后，可以运行查看效果。所有npm命令的具体含义可以查看本文档的npm命令部分\n\n### 打包组件库\"}"
wrk.headers["Content-Type"] = "text/plain; charset=utf-8"
wrk.headers["Origin"] = "http://localhost:63342"
wrk.headers["Referer"] = "http://localhost:63342/leeBlogCli/test/myBlog.html?_ijt=mg0898tqjo365k6ph3bgtldpth"
wrk.headers["User-Agent"] = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36"
